# --- Basic Settings ---
set -g base-index 1
set -g mouse on
set -g status-right ""
set -sg escape-time 0
set-option -g focus-events on

# Change prefix from 'Ctrl+B' to 'Ctrl+A'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Easy config reload (Prefix + r)
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Enable Vi keybindings in copy mode (great for mouse scrolling/searching)
setw -g mode-keys vi

# vim-like pane switching (currently commented out)
# bind -r ^ last-window
# bind -r k select-pane -U
# bind -r j select-pane -D
# bind -r h select-pane -L
# bind -r l select-pane -R

# Ctrl + Tab to go to the next window
bind-key -n BTab next-window

# Pane Borders (Keeping your Tokyo Night colors for the dividers)
set -g pane-border-style 'fg=#414868'
set -g pane-active-border-style 'fg=#7dcfff'

# --- Plugins & Themes ---
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Gruvbox theme setup
set -g @plugin "https://gitlab.com/motaz-shokry/gruvbox-tmux"
set -g @gruvbox-tmux_time_format 24H

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# --- Plugin Settings ---
set -g @continuum-restore 'on'            # Auto-restore on tmux launch
set -g @continuum-save-interval '5'      # Save every 15 minutes
set -g @resurrect-strategy-nvim 'session' # Save Neovim session state

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
